### ISSUE TITLE
How can I add an attribute to hidden input field?

### ISSUE THREAD

**Issue by smohadjer** [bizley/yii2-quill#10]
I need to add an attribute such as form="idOfMyForm" to the hidden input field since my quill editor is outside my form container. But if I add this via an option as below the form attribute ends up on a div container rather than on hidden input field and on submitting the form the input field's value is not submitted.

```
				$form->field($model, 'press_release', [
				'options' => ['form' => 'starterWizard__form']
				])
				->label('Add press release:')
				->widget(\bizley\quill\Quill::class, [
					'toolbarOptions' => 'FULL'
				]);
```

**Comment by bizley** [comment]
Try this one:

```
$form
    ->field($model, 'press_release')
    ->label('Add press release:')
    ->widget(\bizley\quill\Quill::class, [
        'toolbarOptions' => 'FULL',
        'options' => [
            'style' => 'min-height:150px;',
            'form' => 'starterWizard__form'
        ]
    ]);
```

**Comment by bizley** [comment]
Hmm, scratch that, it will not work...

**Comment by bizley** [comment]
The only option now is to override `run()` method.

I'll add new config parameter `hiddenOptions` to make it possible in the next version.

**Comment by smohadjer** [comment]
Thanks. I will fork your repo and update run() method for the time being.

**Comment by bizley** [comment]
Ready in [2.5.0](https://github.com/bizley/yii2-quill/releases/tag/2.5.0). Thanks for the report!

**Comment by smohadjer** [comment]
Perfect! I just upgraded to it and it worked! :)
