### ISSUE TITLE
CDN not working

### ISSUE THREAD

**Issue by Russkazkin** [bizley/yii2-quill#12]
Hello

I have a problem with several ISPs which are blocking quill cdn (Russia).
If it is possible could you please add local copies with possibility to include them if cnd is not available

Thank you

**Comment by bizley** [comment]
Oh, man, I feel sorry for you. Sure thing, I can do that.

**Comment by bizley** [comment]
Released as [2.6.0](https://github.com/bizley/yii2-quill/releases/tag/2.6.0).

**Comment by Russkazkin** [comment]
Thank you very much. I didn't expect it will be so instant. Best regards
