### ISSUE TITLE
Click listener catches unexpected cases

### ISSUE THREAD

**Issue by Nekaravaev** [bizley/yii2-quill#14]
Hey, @bizley!

Thanks for your extension. 

I've noticed that on click by text input on link/embed tooltip, your click event with focus on editor will fired and tooltip hidden without any possibility to interact.

![quill issue 2020-01-15 in 12 21 02](https://user-images.githubusercontent.com/9339389/72421616-e3366580-3791-11ea-9d2e-55073f140aec.gif)

If I remove this event, quill's behave as expected. Why you adds this?

https://github.com/bizley/yii2-quill/blob/aae29b3d7c305b54de85ec3d2c0c66f919463f26/src/Quill.php#L367

**Comment by bizley** [comment]
I have absolutely no idea :grinning: It probably made sense back then though. Anyway, let me just confirm it and I'll prepare patch.

**Comment by bizley** [comment]
It was made for [2.1](https://github.com/bizley/yii2-quill/releases/tag/2.1). Looks like browsers in 2016 had some issues.

Removing it now.

**Comment by bizley** [comment]
Fixed in [2.6.1](https://github.com/bizley/yii2-quill/releases/tag/2.6.1). Thanks for the report!
