### ISSUE TITLE
Latest version of quill

### ISSUE THREAD

**Issue by nadar** [bizley/yii2-quill#4]
HI @bizley - its me again - are there any plans to upgrade this extension to the latest version of quill? 😄

**Comment by bizley** [comment]
Hello.
I'm planning to refresh this extension a bit so yes, it will happen. As for now you can pump up the version by setting `quillVersion` parameter to the newest. `1.3.6` I believe.

**Comment by nadar** [comment]
Works perfect. Thanks.
