### ISSUE TITLE
use non-cdn asset

### ISSUE THREAD

**Issue by akorinek** [bizley/yii2-quill#5]
Hi,

in some installations internet access might be restricted and the quill asset cannot be retrieved from cdn. Could there be a flag to use a local quill asset instead of the cdn url?

**Comment by bizley** [comment]
The thing is that Quill is not providing built distribution files (at least I don't know any) except the CDN ones so there so no easy way to add such flag nicely. Or maybe I'm wrong here - please correct me if so.

To make such a flag work like in your case you can just make few extensions:

1. Prepare your version of QuillAsset.php with configuration for local file.
2. Do the same with HighlightAsset.php and KatexAsset.php if necessary.
3. Extend Quill.php and copy `registerClientScript()` method there from original file but point `QuillAsset` that is registered there to your asset file, you can skip two `if`s for Katex and Highlight if you don't need them.
4. But if you need Katex and Highlight:
    - copy `_katex` and `_highlight` properties declarations.
    - copy whole `prepareOptions()` method.
    - don't skip two `if`s mentioned earlier in `registerClientScript()`.

That's it, should work. Of course when using the widget you don't use `\bizley\quill\Quill` namespace anymore but rather `\your\namespace\for\local\Quill` that you created but you know that already.

**Comment by bizley** [comment]
Since [2.6.0](https://github.com/bizley/yii2-quill/releases/tag/2.6.0) there is an option to use local assets instead of CDN versions.
