### ISSUE TITLE
How to preserve ids and classes on pasted content

### ISSUE THREAD

**Issue by MarcoMoreno** [bizley/yii2-quill#53]
I'm trying to copy/paste text from a Word doc into the Quill editor and but all my ids and classes are being stripped.  Is there a way to configure this module to modify the whitelist and ensure it gets properly preserved to the Yii db?

Specifically, I'm trying to handle footnotes which use anchor links that depend on id attributes.  I'd also like preserve classes so I can style these footnotes.

I know this is probably more of a Quill/Parchment issue, but I've spent days and simply cannot figure out a solution.  I suspect it has to do with adding an attributor or a clipboard matcher but the documentation is very terse and I've gotten nowhere.  I was hoping you could help.

**Comment by bizley** [comment]
The only thing I can think of after some searching is https://quilljs.com/docs/modules/clipboard/#dangerouslypastehtml

**Comment by MarcoMoreno** [comment]
Thanks, @bizley.  I've been trying to understand the clipboard module, but it appears that `dangerouslyPasteHTML` still strips things out according to the clipboard matchers, which I'm struggling to understand.

I appreciate your willingness to help.  BTW, if you're able to come up with a solution, I'm willing to sponser you for your time. :)

**Comment by bizley** [comment]
Thank you for your offer but this is new to me, I would have to do the old try-fail-repeat method so it would not be fair to take money for it.
