### ISSUE TITLE
Is there a way to use the npm module "quill-image-uploader"?

### ISSUE THREAD

**Issue by gb5256** [bizley/yii2-quill#54]
Hi,
love your extension.
Is there a way to include an additional module like the quill-image-uploader?
This is the npm source for it:
https://www.npmjs.com/package/quill-image-uploader
How would I do that?

Thanks for any ideas,
gb5256

**Comment by bizley** [comment]
I'm not sure if this will work but in a theory you could add asset for this package and register it for the view and then just add a module like:

```php
[
    'modules' => [
        'imageUploader' => new JsExpression('your JS here')
    ],
 ]
```

Looks like also you need to add JS to the view with:

```js
Quill.register("modules/imageUploader", ImageUploader);
```

See https://www.yiiframework.com/doc/guide/2.0/en/output-client-scripts

There is a big chance it will work like that. Please let me know.
