### ISSUE TITLE
Retrieve stored information to edit.

### ISSUE THREAD

**Issue by Davidowa** [bizley/yii2-quill#6]
Hello,

I would like to know if you can help me with an inquiry. First, thanks for sharing this solution. I already set up everything and its running smoothly. However, I would like to know if there's a way to retrieve content already stored in the database and modify it using quill.

`<?= 
$form->field($model, 'note')->widget(\bizley\quill\Quill::class, [
'toolbarOptions' => 'FULL',
'options' => ['style' => 'min-height:350px;']
]) 
?>` 

This is the method used according to the instructions. However, is there any way to get something like this?

`
editor.root.innerHTML = $retrievedNote;
`

I hope you can help me with my doubt.

Best wishes,

David

**Comment by bizley** [comment]
Is `$retrievedNote` the same as `$model->note`? If your `$model` is not a new object but rather something fetched from DB `$model->note` should be already set and appear within Quill editor.

**Comment by Davidowa** [comment]
Understood Mr. @bizley ! Let me apply the comment and do some work around. I will report it as soon as possible. Thanks for replying  !

**Comment by Davidowa** [comment]
Hello Mr. @bizley thanks for your answer again! I just tried the way you did and it worked.

**Comment by bizley** [comment]
Glad it works :)
