### ISSUE TITLE
yii2-quill with quill-mention?

### ISSUE THREAD

**Issue by staleo** [bizley/yii2-quill#7]
Hi all,
I'm trying to setup [this brilliant solution](https://github.com/afconsult/quill-mention) on auto mentions in Quill, and feel little stuck.
Can't quite get it -- how do I properly initialize any other modules other than `formula` and `syntax`? And not only initialize with `true`, but also pass several params and callbacks within.
If anybody could help, this would be very nice and kind!
-- best

**Comment by bizley** [comment]
You can initialize Quill with any configuration you want through `configuration` property or just some modules with `modules` property. In your case it should work with config like that (shortened for example purpose)

    [
        'modules' => [
            'mention' => [
                'mentionDenotationChars' => ['@', '#'],
                'source' => new \yii\web\JsExpression('function ...and so on'),
                ... other configuration ...
            ],
        ],
    ]

(this assumes `configuration` key is not used - if it is just put `modules` inside `configuration` array).

Obviously it will not work without Quill Mention JS being added so you need to register this asset after Quill itself but before initialization of editor. I'm not sure right now how difficult it will be but easiest way is to extend this widget with your own class and modify `registerClientScript()` method to add properly all JS (and CSS) in right places.
