### ISSUE TITLE
Typo in Quill.php 'formats' config array key

### ISSUE THREAD

**Issue by fijas** [bizley/yii2-quill#8]
There seems to be a typo in Quill.php on line 258:

https://github.com/bizley/yii2-quill/blob/d7306f188bc906e7af5796195ed9a1f0f3cf66ba/src/Quill.php#L258

It should be 'formats' instead of 'formates'. This causes the formats functionality to not work.

**Comment by bizley** [comment]
Fixed in [2.4.0](https://github.com/bizley/yii2-quill/releases/tag/2.4.0)/[2.2.1](https://github.com/bizley/yii2-quill/releases/tag/2.2.1).

Thank you for report!
